"""Compile application maps into the bundled adjudicator's text format."""

from __future__ import annotations

import hashlib
import tempfile
from pathlib import Path

from diplomacy_app.domain.models import Location, MapDefinition, TerritoryKind, UnitType


def engine_power(power_id: str) -> str:
    return "PWR_" + power_id.upper().replace("-", "_")


def engine_abbreviations(map_definition: MapDefinition) -> dict[object, str]:
    """Return collision-free engine codes independent of user abbreviations."""
    letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    if len(map_definition.territories) > len(letters) ** 2:
        raise ValueError("The standard engine adapter supports at most 676 territories")
    return {
        territory.id: f"Q{letters[index // 26]}{letters[index % 26]}"
        for index, territory in enumerate(map_definition.territories)
    }


def _abbr(map_definition: MapDefinition, location: Location) -> str:
    value = engine_abbreviations(map_definition)[location.territory_id]
    if location.coast_id:
        value += "/" + str(location.coast_id).upper()
    return value


def compile_engine_map(map_definition: MapDefinition) -> str:
    by_id = {item.id: item for item in map_definition.territories}
    codes = engine_abbreviations(map_definition)
    lines = [
        "# Generated by Diplomacy Gamemaster; do not edit.",
        f"BEGIN SPRING {map_definition.default_starting_setup.phase_id.year} MOVEMENT",
        "",
    ]
    for power in map_definition.powers:
        homes = " ".join(codes[value] for value in sorted(power.home_supply_centres))
        lines.append(f"{engine_power(power.id):20} {homes}")
        lines.append("CENTERS")
        lines.append("UNITS")
    owned_home = {value for power in map_definition.powers for value in power.home_supply_centres}
    neutral = [
        codes[item.id]
        for item in map_definition.territories
        if item.is_supply_centre and item.id not in owned_home
    ]
    lines.append("UNOWNED " + " ".join(neutral))
    lines.append("")
    for territory in map_definition.territories:
        aliases = territory.name.casefold().replace(" ", "+")
        lines.append(f"{territory.name:32} = {codes[territory.id]} {aliases}")
        for coast in territory.split_coast_ids:
            lines.append(
                f"{territory.name} ({str(coast).title()} Coast) = "
                f"{codes[territory.id]}/{str(coast).upper()}"
            )
    lines.append("")

    edge_lookup = {
        (edge.origin, edge.destination, edge.unit_type) for edge in map_definition.adjacencies
    }
    fleet_capable = {
        territory.id
        for territory in map_definition.territories
        if territory.kind is TerritoryKind.SEA
        or any(
            edge.origin.territory_id == territory.id and edge.unit_type is UnitType.FLEET
            for edge in map_definition.adjacencies
        )
    }
    for territory in map_definition.territories:
        locations = [Location(territory.id, coast) for coast in territory.split_coast_ids]
        locations.append(Location(territory.id))
        for origin in locations:
            destination_locations = sorted(
                {edge.destination for edge in map_definition.adjacencies if edge.origin == origin},
                key=lambda item: (item.territory_id, item.coast_id or ""),
            )
            if origin.coast_id is None and territory.split_coast_ids:
                coast_destinations = {
                    edge.destination
                    for edge in map_definition.adjacencies
                    if edge.origin.territory_id == territory.id
                    and edge.origin.coast_id is not None
                    and edge.unit_type is UnitType.FLEET
                }
                destination_locations = sorted(
                    set(destination_locations) | coast_destinations,
                    key=lambda item: (item.territory_id, item.coast_id or ""),
                )
            army_here = any(
                edge.origin == origin and edge.unit_type is UnitType.ARMY
                for edge in map_definition.adjacencies
            ) or (origin.coast_id is None and territory.kind is TerritoryKind.LAND)
            fleet_here = any(
                edge.origin == origin and edge.unit_type is UnitType.FLEET
                for edge in map_definition.adjacencies
            )
            if territory.kind is TerritoryKind.SEA:
                terrain = "WATER"
            elif (
                fleet_here
                and origin.coast_id is not None
                or fleet_here
                and not territory.split_coast_ids
            ):
                terrain = "COAST"
            else:
                terrain = "LAND"
            origin_abbreviation = _abbr(map_definition, origin)
            if origin.coast_id is None and territory.split_coast_ids:
                origin_abbreviation = origin_abbreviation.lower()
            abuts: list[str] = []
            for destination in destination_locations:
                army = (origin, destination, UnitType.ARMY) in edge_lookup
                fleet = (origin, destination, UnitType.FLEET) in edge_lookup
                if origin.coast_id is None and territory.split_coast_ids:
                    fleet = any(
                        edge.origin.territory_id == territory.id
                        and edge.origin.coast_id is not None
                        and edge.destination == destination
                        and edge.unit_type is UnitType.FLEET
                        for edge in map_definition.adjacencies
                    )
                token = _abbr(map_definition, destination)
                destination_territory = by_id[destination.territory_id]
                if army and not fleet and (fleet_here or destination.territory_id in fleet_capable):
                    token = token.lower()
                elif (
                    fleet
                    and not army
                    and army_here
                    and destination_territory.kind is TerritoryKind.LAND
                ):
                    token = token[:1].upper() + token[1:].lower()
                abuts.append(token)
            lines.append(f"{terrain:8} {origin_abbreviation:8} ABUTS {' '.join(abuts)}")
    lines.append("")
    return "\n".join(lines)


_PATH_CACHE: dict[str, Path] = {}


def engine_map_path(map_definition: MapDefinition) -> Path:
    text = compile_engine_map(map_definition)
    digest = hashlib.sha256(text.encode()).hexdigest()
    existing = _PATH_CACHE.get(digest)
    if existing and existing.exists():
        return existing
    folder = Path(tempfile.gettempdir()) / "diplomacy-gamemaster-maps"
    folder.mkdir(parents=True, exist_ok=True)
    path = folder / f"{map_definition.id}-{digest[:16]}.map"
    if not path.exists():
        path.write_text(text, encoding="utf-8")
    _PATH_CACHE[digest] = path
    return path


def abbreviation_indexes(
    map_definition: MapDefinition,
) -> tuple[dict[str, Location], dict[Location, str]]:
    forward: dict[str, Location] = {}
    reverse: dict[Location, str] = {}
    codes = engine_abbreviations(map_definition)
    for territory in map_definition.territories:
        base = Location(territory.id)
        abbreviation = codes[territory.id]
        forward[abbreviation] = base
        reverse[base] = abbreviation
        for coast in territory.split_coast_ids:
            location = Location(territory.id, coast)
            value = f"{abbreviation}/{str(coast).upper()}"
            forward[value] = location
            reverse[location] = value
    return forward, reverse
